added stuff

diff --git a/cse270/.github/workflows/main.yml b/cse270/.github/workflows/main.yml
--- a/cse270/.github/workflows/main.yml
+++ b/cse270/.github/workflows/main.yml
@@ -121,6 +121,16 @@ jobs:
         uses: actions/checkout@v4.1.2
       - name: Setup Pages
         uses: actions/configure-pages@v4.0.0
+      - name: Debug workspace
+        run: |
+          echo "Current directory:"
+          pwd
+          echo "Top-level files:"
+          ls
+          echo "Contents of teton:"
+          ls -R teton || echo "teton directory not found"
+          echo "Contents of teton/1.6:"
+          ls -R "teton/1.6" || echo "teton/1.6 directory not found"
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3.0.1
         with:
